services:
  jaeger:
    image: jaegertracing/jaeger:2.9.0
    container_name: jaeger-local
    restart: unless-stopped
    ports:
      - "16686:16686" # UI

  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.115.1
    container_name: otel-collector-local
    restart: unless-stopped
    command: ["--config=/etc/otelcol-contrib/config.yaml"]
    volumes:
      - ./otel-collector.yaml:/etc/otelcol-contrib/config.yaml:ro  # read only
    ports:
      - "9464:9464"   # Prometheus scrape endpoint
      - "13133:13133" # Health check extension
      - "4317:4317"   # OTLP gRPC ingest
      - "4318:4318"   # OTLP HTTP ingest
    depends_on:
      - jaeger
